quarkus.http.port=8080
quarkus.application.name=notification-service

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:ecommerce}
quarkus.datasource.password=${POSTGRES_PASSWORD:ecommerce}
quarkus.datasource.jdbc.url=${POSTGRES_JDBC_URL:jdbc:postgresql://postgres:5432/ecommerce}

# Hibernate/Flyway
quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=notifications
quarkus.flyway.create-schemas=true

# RabbitMQ
rabbitmq-host=${RABBITMQ_HOST:rabbitmq}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:ecommerce}
rabbitmq-password=${RABBITMQ_PASSWORD:ecommerce}

mp.messaging.incoming.notifications-requested-in.connector=smallrye-rabbitmq
mp.messaging.incoming.notifications-requested-in.queue.name=notifications.requested
mp.messaging.incoming.notifications-requested-in.exchange.name=notifications.exchange
mp.messaging.incoming.notifications-requested-in.exchange.type=direct
mp.messaging.incoming.notifications-requested-in.routing-keys=notifications.requested
# mp.messaging.incoming.notifications-requested-in.auto-bind-dlq=true

# Mailpit / SMTP local
quarkus.mailer.from=${MAIL_FROM:no-reply@ecommerce.local}
quarkus.mailer.host=${MAIL_HOST:mailpit}
quarkus.mailer.port=${MAIL_PORT:1025}
# quarkus.mailer.ssl=false
quarkus.mailer.mock=false

app.notification.default-email=${NOTIFICATION_DEFAULT_EMAIL:cliente.demo@ecommerce.local}

# OpenAPI/Swagger
quarkus.swagger-ui.always-include=true

# Observability
quarkus.otel.service.name=notification-service
quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4317}
quarkus.otel.exporter.otlp.protocol=grpc