quarkus.http.port=${PORT:8094}

quarkus.application.name=user-api

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:ecommerce}
quarkus.datasource.password=${DB_PASSWORD:ecommerce}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=${HIBERNATE_LOG_SQL:false}
quarkus.hibernate-orm.database.default-schema=users

mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:publicKey.pem}
mp.jwt.verify.issuer=${JWT_ISSUER:user-api}

smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_LOCATION:privateKey.pem}

app.jwt.issuer=${JWT_ISSUER:user-api}
app.jwt.access-token-minutes=${JWT_ACCESS_TOKEN_MINUTES:30}
app.jwt.refresh-token-minutes=${JWT_REFRESH_TOKEN_MINUTES:10080}

quarkus.datasource.devservices.enabled=false

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Health
quarkus.smallrye-health.root-path=/q/health