quarkus.http.port=${PORT:8096}

quarkus.application.name=order-api

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:ecommerce}
quarkus.datasource.password=${DB_PASSWORD:ecommerce}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}

# Hibernate / Panache
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=${HIBERNATE_LOG_SQL:false}
quarkus.hibernate-orm.database.default-schema=orders

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=0
quarkus.flyway.schemas=orders
quarkus.flyway.locations=db/migration/orders

# Dev Services desligado porque usamos Docker Compose
quarkus.datasource.devservices.enabled=false

# Product API
quarkus.rest-client.product-api.url=${PRODUCT_API_URL:http://localhost:8095}

# OpenAPI / Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Health
quarkus.smallrye-health.root-path=/q/health

# Delivery Estimator API
quarkus.rest-client.delivery-estimator-api.url=${DELIVERY_ESTIMATOR_API_URL:http://localhost:8097}

# RabbitMQ
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:ecommerce}
rabbitmq-password=${RABBITMQ_PASSWORD:ecommerce}
rabbitmq-virtual-host=${RABBITMQ_VIRTUAL_HOST:/}

# Outgoing: order.created
mp.messaging.outgoing.order-created-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.order-created-out.exchange.name=ecommerce.events
mp.messaging.outgoing.order-created-out.exchange.type=topic
mp.messaging.outgoing.order-created-out.exchange.declare=false
mp.messaging.outgoing.order-created-out.default-routing-key=order.created

# Outgoing: order.canceled
mp.messaging.outgoing.order-canceled-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.order-canceled-out.exchange.name=ecommerce.events
mp.messaging.outgoing.order-canceled-out.exchange.type=topic
mp.messaging.outgoing.order-canceled-out.exchange.declare=false
mp.messaging.outgoing.order-canceled-out.default-routing-key=order.canceled

# Incoming: fraud.approved
mp.messaging.incoming.fraud-approved-in.connector=smallrye-rabbitmq
mp.messaging.incoming.fraud-approved-in.queue.name=order.fraud-approved
mp.messaging.incoming.fraud-approved-in.exchange.name=ecommerce.events
mp.messaging.incoming.fraud-approved-in.exchange.type=topic
mp.messaging.incoming.fraud-approved-in.exchange.declare=false
mp.messaging.incoming.fraud-approved-in.queue.declare=false
mp.messaging.incoming.fraud-approved-in.routing-keys=fraud.approved

# Incoming: fraud.rejected
mp.messaging.incoming.fraud-rejected-in.connector=smallrye-rabbitmq
mp.messaging.incoming.fraud-rejected-in.queue.name=order.fraud-rejected
mp.messaging.incoming.fraud-rejected-in.exchange.name=ecommerce.events
mp.messaging.incoming.fraud-rejected-in.exchange.type=topic
mp.messaging.incoming.fraud-rejected-in.exchange.declare=false
mp.messaging.incoming.fraud-rejected-in.queue.declare=false
mp.messaging.incoming.fraud-rejected-in.routing-keys=fraud.rejected

# Outgoing: product.stock.reserve
mp.messaging.outgoing.stock-reservation-requested-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.stock-reservation-requested-out.exchange.name=ecommerce.events
mp.messaging.outgoing.stock-reservation-requested-out.exchange.type=topic
mp.messaging.outgoing.stock-reservation-requested-out.exchange.declare=false
mp.messaging.outgoing.stock-reservation-requested-out.default-routing-key=product.stock.reserve

# Incoming: stock.reserved
mp.messaging.incoming.stock-reserved-in.connector=smallrye-rabbitmq
mp.messaging.incoming.stock-reserved-in.queue.name=order.stock-reserved
mp.messaging.incoming.stock-reserved-in.exchange.name=ecommerce.events
mp.messaging.incoming.stock-reserved-in.exchange.type=topic
mp.messaging.incoming.stock-reserved-in.exchange.declare=false
mp.messaging.incoming.stock-reserved-in.queue.declare=false
mp.messaging.incoming.stock-reserved-in.routing-keys=stock.reserved

# Incoming: stock.rejected
mp.messaging.incoming.stock-rejected-in.connector=smallrye-rabbitmq
mp.messaging.incoming.stock-rejected-in.queue.name=order.stock-rejected
mp.messaging.incoming.stock-rejected-in.exchange.name=ecommerce.events
mp.messaging.incoming.stock-rejected-in.exchange.type=topic
mp.messaging.incoming.stock-rejected-in.exchange.declare=false
mp.messaging.incoming.stock-rejected-in.queue.declare=false
mp.messaging.incoming.stock-rejected-in.routing-keys=stock.rejected

# Outbox
app.outbox.poll-interval=2s

# Observability
quarkus.otel.enabled=${OTEL_ENABLED:true}
quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}

# Metrics
quarkus.micrometer.export.prometheus.enabled=true