quarkus.http.port=${PORT:8096}

quarkus.application.name=order-api

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:ecommerce}
quarkus.datasource.password=${DB_PASSWORD:ecommerce}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}

# Hibernate / Panache
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=${HIBERNATE_LOG_SQL:false}
quarkus.hibernate-orm.database.default-schema=orders

# Dev Services desligado porque usamos Docker Compose
quarkus.datasource.devservices.enabled=false

# Product API
quarkus.rest-client.product-api.url=${PRODUCT_API_URL:http://localhost:8095}

# OpenAPI / Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Health
quarkus.smallrye-health.root-path=/q/health

# Delivery Estimator API
quarkus.rest-client.delivery-estimator-api.url=${DELIVERY_ESTIMATOR_API_URL:http://localhost:8097}