quarkus.http.port=${PORT:8098}

quarkus.application.name=fraud-detector-api

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:ecommerce}
quarkus.datasource.password=${DB_PASSWORD:ecommerce}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}

# Hibernate / Panache
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=${HIBERNATE_LOG_SQL:false}
quarkus.hibernate-orm.database.default-schema=fraud

# Dev Services desligado porque usamos Docker Compose
quarkus.datasource.devservices.enabled=false

# RabbitMQ
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:ecommerce}
rabbitmq-password=${RABBITMQ_PASSWORD:ecommerce}
rabbitmq-virtual-host=${RABBITMQ_VIRTUAL_HOST:/}

# Incoming: consome eventos order.created
mp.messaging.incoming.order-created-in.connector=smallrye-rabbitmq
mp.messaging.incoming.order-created-in.queue.name=fraud.order-created
mp.messaging.incoming.order-created-in.exchange.name=ecommerce.events
mp.messaging.incoming.order-created-in.exchange.type=topic
mp.messaging.incoming.order-created-in.exchange.declare=false
mp.messaging.incoming.order-created-in.queue.declare=false
mp.messaging.incoming.order-created-in.routing-keys=order.created

# Outgoing: fraud.approved
mp.messaging.outgoing.fraud-approved-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.fraud-approved-out.exchange.name=ecommerce.events
mp.messaging.outgoing.fraud-approved-out.exchange.type=topic
mp.messaging.outgoing.fraud-approved-out.exchange.declare=false
mp.messaging.outgoing.fraud-approved-out.default-routing-key=fraud.approved

# Outgoing: fraud.rejected
mp.messaging.outgoing.fraud-rejected-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.fraud-rejected-out.exchange.name=ecommerce.events
mp.messaging.outgoing.fraud-rejected-out.exchange.type=topic
mp.messaging.outgoing.fraud-rejected-out.exchange.declare=false
mp.messaging.outgoing.fraud-rejected-out.default-routing-key=fraud.rejected

# OpenAPI / Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Health
quarkus.smallrye-health.root-path=/q/health

# Observability
quarkus.otel.enabled=${OTEL_ENABLED:true}
quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}

# Metrics
quarkus.micrometer.export.prometheus.enabled=true

# Fraud ML - trained model loading
app.fraud-ml.enabled=${APP_FRAUD_ML_ENABLED:true}
app.fraud-ml.model-path=${APP_FRAUD_ML_MODEL_PATH:/models/fraud/fraud-tribuo-v1.model}