quarkus.http.port=8080
quarkus.application.name=ai-chat-bff

# REST clients internos
quarkus.rest-client.product-api.url=${PRODUCT_API_URL:http://product-api:8080}
quarkus.rest-client.delivery-estimator-api.url=${DELIVERY_ESTIMATOR_API_URL:http://delivery-estimator-api:8080}
quarkus.rest-client.order-api.url=${ORDER_API_URL:http://order-api:8080}
quarkus.rest-client.product-api.scope=jakarta.inject.Singleton
quarkus.rest-client.delivery-estimator-api.scope=jakarta.inject.Singleton
quarkus.rest-client.order-api.scope=jakarta.inject.Singleton
# Ollama local via Docker host
quarkus.langchain4j.ollama.base-url=${OLLAMA_BASE_URL:http://host.docker.internal:11434}
quarkus.langchain4j.ollama.chat-model.model-name=${OLLAMA_CHAT_MODEL:llama3.2:latest}
quarkus.langchain4j.ollama.chat-model.temperature=0
quarkus.langchain4j.timeout=120s

# OpenAPI/Swagger
quarkus.swagger-ui.always-include=true

# Health
quarkus.smallrye-health.root-path=/q/health

# Observability
quarkus.otel.service.name=ai-chat-bff
quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4317}
quarkus.otel.exporter.otlp.protocol=grpc