quarkus.http.port=${PORT:8095}

quarkus.application.name=product-api

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:ecommerce}
quarkus.datasource.password=${DB_PASSWORD:ecommerce}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}

# Hibernate / Panache
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=${HIBERNATE_LOG_SQL:false}
quarkus.hibernate-orm.database.default-schema=products

# Dev Services desligado porque usamos Docker Compose
quarkus.datasource.devservices.enabled=false

# OpenAPI / Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Health
quarkus.smallrye-health.root-path=/q/health

# RabbitMQ
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:ecommerce}
rabbitmq-password=${RABBITMQ_PASSWORD:ecommerce}
rabbitmq-virtual-host=${RABBITMQ_VIRTUAL_HOST:/}

# Incoming: product.stock.reserve
mp.messaging.incoming.stock-reservation-in.connector=smallrye-rabbitmq
mp.messaging.incoming.stock-reservation-in.queue.name=product.stock-reservation
mp.messaging.incoming.stock-reservation-in.exchange.name=ecommerce.events
mp.messaging.incoming.stock-reservation-in.exchange.type=topic
mp.messaging.incoming.stock-reservation-in.exchange.declare=false
mp.messaging.incoming.stock-reservation-in.queue.declare=false
mp.messaging.incoming.stock-reservation-in.routing-keys=product.stock.reserve

# Outgoing: stock.reserved
mp.messaging.outgoing.stock-reserved-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.stock-reserved-out.exchange.name=ecommerce.events
mp.messaging.outgoing.stock-reserved-out.exchange.type=topic
mp.messaging.outgoing.stock-reserved-out.exchange.declare=false
mp.messaging.outgoing.stock-reserved-out.default-routing-key=stock.reserved

# Outgoing: stock.rejected
mp.messaging.outgoing.stock-rejected-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.stock-rejected-out.exchange.name=ecommerce.events
mp.messaging.outgoing.stock-rejected-out.exchange.type=topic
mp.messaging.outgoing.stock-rejected-out.exchange.declare=false
mp.messaging.outgoing.stock-rejected-out.default-routing-key=stock.rejected

# Observability
quarkus.otel.enabled=${OTEL_ENABLED:true}
quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}

# Metrics
quarkus.micrometer.export.prometheus.enabled=true